### PR TITLE
Added AVR PSTR() compatibility

### PR DESCRIPTION
**Pull request by mickjc750**
Added printf_P (and friends) for compatibility with AVR.
Additions require the symbol PLATFORM_AVR to be defined, there are no changes to compiled code for non-avr targets.
Macros printf_SL() (and friends) provide an easy way to make code portable between AVR and other targets.
printf_SL() also allows the compiler to check argument types based on the formatting string, this is normally not possible with printf_P() as the formatting string is hidden within the PSTR() compound statement.

This is a heavy addition, and I'm not sure how many people actually want AVR PSTR() compatibility. If it is desired, and I have implemented this in some grossly inappropriate way (I don't collaborate a lot), I am open to suggestions and willing to re-work it.

### CODE REVIEW

**Comment by ledvinap** [comment]
Maybe it would be better to define macros that access progmem and compile whole printf code for PGM and non-PGM version. There will be some code-size penalty, but changes to code will be much smaller. And in lot of use cases, you can compile PGM version only.

**Comment by mickjc750** [comment]
> Maybe it would be better to define macros that access progmem and compile whole printf code for PGM and non-PGM version. There will be some code-size penalty, but changes to code will be much smaller. And in lot of use cases, you can compile PGM version only.

Hi ledvinap, sorry I'm not 100% clear on what you mean.
 Do you mean duplicate the _vsnprintf() function for pgm and non-pgm? This would allow removing the 'bool is_pgm', which would be nice, I hate that access of is_pgm is hidden in a macro, but any future changes to _vsnprintf() would need to be mirrored in both versions.
 Or is there some way to compile the same file twice in one build with different symbols defined? I'm not sure how this could work in a Makefile.
 Or do you mean to create a a new source file printf_P.c ?

**Comment by ledvinap** [comment]
@mickjc750 : Duplicating code will only cause problems, the idea was to keep modifications to minimum.

In makefile, you can create new rule (even something like %.pgm.o), pass `-D PGM_BUILD` and link both resulting  objects.
With preprocessor, you can include printf.c twice (ideally renaming it to .inc).
Or include printf.c again in printf.c, using #defines to prevent infinite recursion.

All variants are quite ugly, but that may be acceptable. And printf source code may be almost unchanged (possibly using AVR-sprecific .h files), so maintaining it will be easier.

**Comment by mickjc750** [comment]
@ledvinap 
Thanks, I understand. These are good ideas.

I believe option #2, moving the _vsnprintf() and _atoi() variants into an .inc file, would be the easiest for most users to understand (at the cost of an extra file).

 Option #3, including printf.c within printf.c, could be ok with some well named #defines and well explained #ifdefs, but would still be less clear than option #2 (but no extra file needed).

 Option #1, the Makefile rule, would confuse the most people (including me somewhat). Many users stay within their IDE and know little (if anything) about Makefiles.

 Thanks a lot for your suggestions. I will resubmit a PR soon using an .inc file. Unless @mpaland has another preference.

**Comment by ledvinap** [comment]
@mickjc750 : It's @mpaland call, but I doubt that this will get merged. So variant that is easy to rebase on upstream is good idea, #2 is probably best (git rename + extra wrapper file)

**Comment by eyalroz** [comment]
@mickjc750 , @ledvinap : Of course this isn't my repository, nor my PR, but - it seems the changes here are basically a wrapper which could be maintained separately, and is not generally relevant (i.e. only relevant for people who work on the AVR microcontroller platform). So, what is the rationale for wanting to merge it into this repository, which is basically free of platform idiosyncracies?

**Comment by mickjc750** [comment]
@eyalroz Thanks for the energy you're putting into printf, I intend on following your fork.

 There may be some misunderstanding as to my intentions here, possibly due to my ignorance of public git repositories. I have no intention of merging my current fork with mpaland/printf. Yet every time I push one of my own commits I get a notification "mickjc750 wants to merge X commits..." no I don't.

 I have a number of active projects in AVR and STM32, and struggle to find graceful ways of supporting both with my modules. Given that AVR requires a different storage class for string constants (without wasting precious RAM), I'm very interested (and somewhat skeptical) to know how this might be supported with a separate wrapper. Keeping in mind, the AVR version may need to access format strings from both RAM and program memory.

 The rational for supporting AVR; printf is intended for microcontrollers, and AVR is still a popular family of microcontrollers. (Not that I would use one in a new project personally).

**Pull request closed without merging**
